# Generated by Django 5.2.4 on 2026-01-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
