# Generated by Django 5.2.4 on 2026-01-22 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(default='', help_text='Contact phone number', max_length=20, validators=[django.core.validators.MinLengthValidator(10)]),
            preserve_default=False,
        ),
    ]
