# Generated by Django 5.2.4 on 2026-01-29 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_alter_lead_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('PRIMARY', 'Primary Assignment'), ('SUB', 'Sub Assignment'), ('REASSIGNMENT', 'Reassignment')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='lead',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Who assigned this lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_assigned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_assigned_by',
            field=models.ForeignKey(blank=True, help_text='Manager who sub-assigned to junior', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads_sub_assigned_by_me', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='sub_assigned_to',
            field=models.ForeignKey(blank=True, help_text='Junior employee handling the lead', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Primary assignee (Manager/Department Head)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['sub_assigned_to'], name='leads_lead_sub_ass_65f391_idx'),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='made_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadassignment',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='leads.lead'),
        ),
    ]
