# Generated by Django 5.2.4 on 2026-02-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_leadassignment_lead_assigned_by_lead_sub_assigned_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'Automation'), ('OTHER', 'Other')], max_length=20),
        ),
    ]
