# Generated by Django 5.2.4 on 2026-02-23 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(help_text='Contact phone number', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
