# Generated by Django 5.2.4 on 2026-03-18 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0020_alter_lead_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('QUALIFIED', 'Qualified'), ('INTERESTED', 'Interested'), ('NOT_INTERESTED', 'Not Interested'), ('REGISTERED', 'Registered'), ('CONVERTED', 'Converted'), ('LOST', 'Lost'), ('CNR', 'Could Not Reach')], default='ENQUIRY', help_text='Current status of the lead', max_length=20),
        ),
    ]
