# Generated by Django 5.2.4 on 2026-03-18 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0021_alter_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('ENQUIRY', 'Enquiry'), ('QUALIFIED', 'Qualified'), ('NOT_INTERESTED', 'Not Interested'), ('CONVERTED', 'Converted'), ('CNR', 'Could Not Reach')], default='ENQUIRY', help_text='Current status of the lead', max_length=20),
        ),
    ]
