# Generated by Django 5.2.4 on 2026-03-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0023_alter_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.CharField(blank=True, choices=[('WHATSAPP', 'WhatsApp'), ('INSTAGRAM', 'Instagram'), ('WEBSITE', 'Website'), ('WALK_IN', 'Walk-in'), ('AUTOMATION', 'Automation'), ('OTHER', 'Other'), ('ADS', 'Ads')], max_length=20, null=True),
        ),
    ]
