# Generated by Django 5.2.4 on 2026-04-07 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0026_alter_lead_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
                ('follow_up_date', models.DateField()),
                ('follow_up_time', models.TimeField(blank=True, null=True)),
                ('followup_type', models.CharField(choices=[('call', 'Call'), ('whatsapp', 'WhatsApp'), ('email', 'Email'), ('meeting', 'Meeting')], default='call', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('not_interested', 'Not Interested'), ('rescheduled', 'Rescheduled')], default='pending', max_length=20)),
                ('converted_to_lead', models.BooleanField(default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='leads.lead')),
            ],
            options={
                'ordering': ['follow_up_date', 'follow_up_time'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('followup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='leads.followup')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['follow_up_date'], name='leads_follo_follow__ba7a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['status'], name='leads_follo_status_d8909c_idx'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['assigned_to'], name='leads_follo_assigne_44c12b_idx'),
        ),
    ]
