# Generated by Django 5.2.4 on 2026-01-22 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_attendancedocument_delete_attendance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penalty',
            name='employee',
        ),
        migrations.AlterModelOptions(
            name='penalty',
            options={'ordering': ['-date'], 'verbose_name': 'Penalty', 'verbose_name_plural': 'Penalties'},
        ),
        migrations.AddField(
            model_name='penalty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='amount',
            field=models.IntegerField(blank=True, default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='penalty',
            name='month',
            field=models.CharField(max_length=100, verbose_name='Month'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
