# Generated by Django 5.2.4 on 2025-12-22 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'General Manager'), ('OPS', 'Operations Manager'), ('ADM_MANAGER', 'Admission Manager'), ('ADM_EXEC', 'Admission Executive'), ('PROCESSING', 'Processing Executive'), ('MEDIA', 'Media Team'), ('TRAINER', 'Trainer'), ('BUSINESS_HEAD', 'Business Head'), ('BUSINESS DEVELOPMENT MANAGER', 'Business development manager'), ('CM', 'Center Manager'), ('HR', 'Human Resources'), ('FOE', 'FOE Cum TC')], max_length=30),
        ),
    ]
