# Generated by Django 5.2.4 on 2026-01-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'General Manager'), ('OPS', 'Operations Manager'), ('ADM_MANAGER', 'Admission Manager'), ('ADM_EXEC', 'Admission Executive'), ('PROCESSING', 'Processing Executive'), ('MEDIA', 'Media Team'), ('TRAINER', 'Trainer'), ('BUSINESS_HEAD', 'Business Head'), ('BUSINESS_DEVELOPMENT_MANAGER', 'BDM'), ('CM', 'Center Manager'), ('HR', 'Human Resources'), ('FOE', 'FOE Cum TC')], max_length=30),
        ),
    ]
