# Generated by Django 5.2.4 on 2026-01-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_join_date_user_salary_delete_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'General Manager'), ('OPS', 'Operations Manager'), ('ADM_MANAGER', 'Admission Manager'), ('ADM_EXEC', 'Admission Executive'), ('PROCESSING', 'Processing Executive'), ('MEDIA', 'Media Team'), ('TRAINER', 'Trainer'), ('BUSINESS_HEAD', 'Business Head'), ('BDM', 'Business Development Manager'), ('CM', 'Center Manager'), ('HR', 'Human Resources'), ('FOE', 'FOE Cum TC'), ('ACCOUNTS', 'Accounts')], db_index=True, max_length=100),
        ),
    ]
