# Generated by Django 5.2.4 on 2026-04-11 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Activity Log', 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='activity_type',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_SUB_ASSIGNED', 'Lead Sub-Assigned'), ('LEAD_UNASSIGNED', 'Lead Unassigned'), ('LEAD_PROCESSING_UPDATED', 'Lead Processing Status Updated'), ('LEAD_REMARK_UPDATED', 'Lead Remark Updated'), ('LEAD_DELETED', 'Lead Deleted'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_UPDATED', 'Follow-Up Updated'), ('FOLLOWUP_STATUS_CHANGED', 'Follow-Up Status Changed'), ('FOLLOWUP_CONVERTED', 'Follow-Up Converted to Lead'), ('FOLLOWUP_DELETED', 'Follow-Up Deleted'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_OVERDUE', 'Task Marked Overdue'), ('TASK_DELETED', 'Task Deleted'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_ACTIVATED', 'Staff Activated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('STAFF_DELETED', 'Staff Deleted'), ('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('MICROWORK_CREATED', 'Micro Work Created'), ('MICROWORK_COMPLETED', 'Micro Work Completed'), ('MICROWORK_DELETED', 'Micro Work Deleted'), ('SYSTEM_MIGRATED', 'System Migrated')], db_index=True, default='SYSTEM_MIGRATED', max_length=60),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(db_index=True, default='SYSTEM_MIGRATED', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action'], name='accounts_ac_action_fde492_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['entity_type'], name='accounts_ac_entity__3bd5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['created_at'], name='accounts_ac_created_936747_idx'),
        ),
    ]
