# Generated by Django 5.2.4 on 2026-04-11 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_activitylog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LEAD_CREATED', 'Lead Created'), ('LEAD_UPDATED', 'Lead Updated'), ('LEAD_STATUS_CHANGED', 'Lead Status Changed'), ('LEAD_ASSIGNED', 'Lead Assigned'), ('LEAD_SUB_ASSIGNED', 'Lead Sub-Assigned'), ('LEAD_UNASSIGNED', 'Lead Unassigned'), ('LEAD_PROCESSING_UPDATED', 'Lead Processing Status Updated'), ('LEAD_REMARK_UPDATED', 'Lead Remark Updated'), ('LEAD_DELETED', 'Lead Deleted'), ('FOLLOWUP_CREATED', 'Follow-Up Created'), ('FOLLOWUP_UPDATED', 'Follow-Up Updated'), ('FOLLOWUP_STATUS_CHANGED', 'Follow-Up Status Changed'), ('FOLLOWUP_CONVERTED', 'Follow-Up Converted to Lead'), ('FOLLOWUP_DELETED', 'Follow-Up Deleted'), ('TASK_CREATED', 'Task Created'), ('TASK_UPDATED', 'Task Updated'), ('TASK_STATUS_CHANGED', 'Task Status Changed'), ('TASK_COMPLETED', 'Task Completed'), ('TASK_CANCELLED', 'Task Cancelled'), ('TASK_OVERDUE', 'Task Marked Overdue'), ('TASK_DELETED', 'Task Deleted'), ('STAFF_CREATED', 'Staff Created'), ('STAFF_UPDATED', 'Staff Updated'), ('STAFF_ACTIVATED', 'Staff Activated'), ('STAFF_DEACTIVATED', 'Staff Deactivated'), ('STAFF_DELETED', 'Staff Deleted'), ('USER_LOGIN', 'User Logged In'), ('USER_LOGOUT', 'User Logged Out'), ('MICROWORK_CREATED', 'Micro Work Created'), ('MICROWORK_COMPLETED', 'Micro Work Completed'), ('MICROWORK_DELETED', 'Micro Work Deleted')], db_index=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='entity_type',
            field=models.CharField(db_index=True, default='UNKNOWN', max_length=50),
        ),
    ]
