# Generated by Django 5.2.4 on 2026-02-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyreport',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
