# Generated by Django 5.2.4 on 2026-02-11 09:32

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_dailyreport_original_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attached_file', cloudinary.models.CloudinaryField(help_text='Upload any relevant file', max_length=255, verbose_name='Attached File')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.dailyreport')),
            ],
        ),
    ]
