# Generated by Django 5.2.4 on 2026-02-11 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_dailyreportattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyreport',
            name='attached_file',
        ),
        migrations.RemoveField(
            model_name='dailyreport',
            name='original_filename',
        ),
    ]
