# Generated by Django 5.2.4 on 2026-02-11 11:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_remove_dailyreport_attached_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyreportattachment',
            name='attached_file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
