# Generated by Django 5.2.4 on 2026-02-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('caller_number', models.CharField(max_length=20)),
                ('agent_number', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.URLField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
