# Generated by Django 5.2.4 on 2026-03-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoxbayCallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_uuid', models.CharField(blank=True, max_length=100, null=True)),
                ('caller_number', models.CharField(blank=True, max_length=20, null=True)),
                ('agent_number', models.CharField(blank=True, max_length=20, null=True)),
                ('call_status', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('recording_url', models.TextField(blank=True, null=True)),
                ('call_start', models.DateTimeField(blank=True, null=True)),
                ('call_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CallLog',
        ),
    ]
