# Generated by Django 5.2.4 on 2026-03-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0002_voxbaycalllog_delete_calllog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voxbaycalllog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='call_type',
            field=models.CharField(blank=True, choices=[('incoming', 'Incoming'), ('outgoing', 'Outgoing')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='called_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='caller_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='conversation_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='destination',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='dtmf',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='transferred_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='voxbaycalllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voxbaycalllog',
            name='agent_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='voxbaycalllog',
            name='call_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='voxbaycalllog',
            name='call_uuid',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='voxbaycalllog',
            name='caller_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddIndex(
            model_name='voxbaycalllog',
            index=models.Index(fields=['call_status'], name='telephony_v_call_st_dc4e18_idx'),
        ),
        migrations.AddIndex(
            model_name='voxbaycalllog',
            index=models.Index(fields=['call_type'], name='telephony_v_call_ty_4f38e7_idx'),
        ),
        migrations.AddIndex(
            model_name='voxbaycalllog',
            index=models.Index(fields=['created_at'], name='telephony_v_created_b1afb7_idx'),
        ),
    ]
