# Generated by Django 5.2.4 on 2026-03-09 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telephony', '0003_alter_voxbaycalllog_options_voxbaycalllog_call_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoxbayAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, help_text='Full phone number as sent by Voxbay, e.g. 918089040107', max_length=30, unique=True)),
                ('extension', models.CharField(blank=True, help_text='Ext No. from Voxbay, e.g. 513', max_length=20, null=True)),
                ('did_number', models.CharField(blank=True, help_text='DID No. from Voxbay, e.g. 914847173519', max_length=30, null=True)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
